name: toyyibpay_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.2
homepage: https://github.com/fadhilx/toyyibpay-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.4
  http: ^0.12.0+4
  meta: ^1.1.8
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  json_to_model: ^1.3.9
  json_serializable:
